---
title: "pdftools"
author: "Richard White"
date: "04/10/2022"
output:
  md_document:
    variant: markdown_github
---

```{r load_packages, message = FALSE}
library('pdftools')
library('palmerpenguins')
library('ggplot2')
```

```{r knitr-options, include=FALSE, message=FALSE}
library('knitr')
opts_chunk$set(include=TRUE, echo=TRUE, warning = FALSE, message = FALSE)
```

The [pdftools](https://cran.r-project.org/web/packages/pdftools/index.html) package can be used to split and combine pages from pdfs.

```{r test-pdf}
# create a test pdf
pdf('test-all.pdf')
ggplot(data = penguins) +
  geom_point(aes(x = bill_length_mm, y = bill_depth_mm))
ggplot(data = penguins) +
  geom_histogram(aes(x = body_mass_g))
ggplot(data = penguins) +
  geom_boxplot(aes(x = species, y = body_mass_g))
ggplot(data = na.omit(penguins)) +
  geom_boxplot(aes(x = species, y = body_mass_g, fill = sex)) +
  scale_fill_brewer(palette = 'Dark2')
dev.off()
```

To produce a separate pdf file for each page, use `pdf_split`.

```{r}
pdf_split('test-all.pdf', output = 'test-split')
```

To create a new pdf with a subset of the pages, use `pdf_subset`
```{r}
pdf_subset('test-all.pdf', pages = 1:2, output = 'test-subset-1.pdf')
pdf_subset('test-all.pdf', pages = 3:4, output = 'test-subset-2.pdf')
```

To combine several pdfs into one, use `pdf_combine`
```{r}
pdf_combine(c('test-subset-2.pdf', 'test-all.pdf', 'test-subset-1.pdf'),
            output = 'test-combined.pdf')
```

```{r tidy-up, echo=FALSE}
unlink(c('test-all.pdf', 'test-split*.pdf', 
         'test-subset-*.pdf', 'test-combined.pdf'),
       expand = TRUE)
```